name: Deploy

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Configure AWS
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
        aws-region: ap-south-1

    - name: Login to ECR
      run: |
        aws ecr get-login-password --region ap-south-1 \
        | docker login --username AWS \
        --password-stdin ${{ secrets.ECR_URL }}

    - name: Build & Push Backend
      run: |
        docker build -t backend ./backend
        docker tag backend:latest ${{ secrets.ECR_URL }}/backend:latest
        docker push ${{ secrets.ECR_URL }}/backend:latest

    - name: Build & Push Frontend
      run: |
        docker build -t frontend ./frontend
        docker tag frontend:latest ${{ secrets.ECR_URL }}/frontend:latest
        docker push ${{ secrets.ECR_URL }}/frontend:latest

    - name: Deploy
      run: |
        aws eks update-kubeconfig --name my-cluster --region ap-south-1
        kubectl apply -f k8s/
