name: Deploy

on:
  push:
    branches: [ "main" ]

env:
  AWS_REGION: ap-south-1
  CLUSTER_NAME: React-cluster  

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Configure AWS
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
        aws-region:  ${{ env.AWS_REGION }}

    - name: Login to ECR
      uses: aws-actions/amazon-ecr-login@v2

    - name: Build & Push Backend
      run: |
        docker build -t backend ./backend
        docker tag backend:latest ${{ secrets.ECR_URL }}:latest
        docker push ${{ secrets.ECR_URL }}:latest

    - name: Build & Push Frontend
      run: |
        docker build -t frontend ./frontend
        docker tag frontend:latest ${{ secrets.ECR_URL }}:latest
        docker push ${{ secrets.ECR_URL }}:latest

    - name: Deploy
      run: |
        aws eks update-kubeconfig --name $CLUSTER_NAME --region $AWS_REGION
        kubectl apply -f k8s/
        kubectl get all -n three-tier

